config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  # bookmark/new.html.erb
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully destroyed.'
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
 before_action :set_list, only: [:show, :destroy]

 # GET /lists
  def index
    @lists = List.all
    @movies = Movie.all
  end

  # GET /lists/1
  def show
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # POST /lists
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), notice: 'List was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, notice: 'List was successfully destroyed.'
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_new.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a movie to your <%= @list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
       <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
          <%= f.association :movie, prompt: "Select a movie", input_html: { data: { controller: "select2" } } %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="form py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie, prompt: 'Select a movie', input_html: { data: { controller: 'select2' }} %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
   <%= render 'shared/navbar' %>

    <%= yield %>

    <%# <script src="app/javascript/channels/index.js"></script> %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner">
  <div class="container">
    <span class="typed-js" data-controller="typed-js"></span>
  </div>
</div>

<div class="cards-home-container">
  <div class="cards-home">
    <% @lists.each do |list| %>
      <%= link_to list_path(list), class: "text-decoration-none" do %>
        <div class="card-home" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : @movies.sample.poster_url %>)">
          <%= list.name %>
        </div>
      <% end %>
    <% end %>
    <%= link_to new_list_path(@list), class: "text-decoration-none" do %>
      <div class="card-home" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @movies.sample.poster_url %>)">
        Create a new list
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3 ">
      <div class="p-3 shadow form-list-new">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Drama' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-info' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%# HEADER %>
<div class="header-container">
    <div class="header-text-title">
      <h1><%= @list.name %></h1>
    </div>
    <div class="header-text-action">

      <button type="button" class="modal-button" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Create a bookmark
      </button> |
      <%= link_to "Delete this list", list_path(@list), method: :delete, class: "header-delete-button", data: { confirm: "Are you sure you want to delete this list?" } %>
    </div>
  </div>
</div>

<%# MODAL %>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" class="rounded">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a movie to your <%= @list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
       <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
          <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: { data: { controller: 'select2' }} %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= f.submit class: 'btn btn-info' %>
        <% end %>
      </div>
    </div>
  </div>
</div>



<%# NOT USED MODAL %>
<%# <%# Keep otherwise above modal doesn't display properly %>
<%# I don't know the reason for %> %>
<div class="modal fade" id="newMovieModal" tabindex="-1" aria-labelledby="newModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newMovieModalLabel">Add a movie to your <%= @list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: "Enter a new comment about the movie" %>
          <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: { data: { controller: "select2" } } %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
      </div>
    </div>
  </div>
</div>

<%# BREAK LINE  %>
<hr class="header-break">

<%# CARDS %>
<div class="cards-container">
  <div class="cards" id="sortable-movie">
   <% @list.bookmarks.each do |bookmark| %>
      <div class="card card-list" >
        <img src=<%= bookmark.movie.poster_url %> class="card-picture" alt="movie-poster">
        <div class="card-body" >
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p class="card-comment">"<%= bookmark.comment %>"</p>
          <% if bookmark.movie.overview.size > 200 %>
            <p class="card-overview"><%= bookmark.movie.overview.first(200) %> [...]</p>
          <% else %>
            <p class="card-overview"><%= bookmark.movie.overview%></p>
          <% end %>
          <%= link_to "Delete this bookmark", bookmark_path(bookmark), method: :delete, class: "card-delete-button", data: { confirm: "Are you sure you want to delete this bookmark?" } %>
        </div>
      </div>
    <% end %>


      <%# ADD A BOOK MARK - CARD %>
      <div class="card card-add">
        <img src=<%= @movies.sample.poster_url %> class="card-picture" alt="movie-poster">
        <div class="card-body">
          <button type="button" class="card-create-button" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Create a bookmark
          </button>
          <p class="card-comment card-comment-add">"Write your bookmark"</p>
        </div>
      </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav data-controller="navbar">
  <%= link_to "The Rails WatchList", lists_path, class: "navbar-logo" %>
  <%= link_to "Home", lists_path, class: "navbar-link" %>
  <%= link_to "Create a list", new_list_path, class: "navbar-link" %>
</nav>